"""empty message

Revision ID: 96745022dc5b
Revises: 
Create Date: 2021-06-27 15:01:32.481294

"""
from sqlalchemy import func

from alembic import op
import sqlalchemy as sa
import csv


# revision identifiers, used by Alembic.
revision = '96745022dc5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    meter_usages = op.create_table('meter_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_usages_time'), 'meter_usages', ['time'], unique=False)

    ##add sample data to meter usage table
    seed_data = []
    with open("seed_data/meterusage.csv", "r") as csvfile:
        reader = csv.reader(csvfile)

        for row in reader:
            seed_data.append({"value": row[1], "time": row[0]})

    op.bulk_insert(
        meter_usages,
        seed_data
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_usages_time'), table_name='meter_usages')
    op.drop_table('meter_usages')
    # ### end Alembic commands ###
